steps:
  test:
    when:
      - event: push
        branch: main
      - event: pull_request
        branch: main
    image: unafterthought/tree-sitter:0.0.1
    commands:
      - tree-sitter generate
      - if [ "$(git status --porcelain)" ]; then exit 1; fi
      - tree-sitter test && tree-sitter parse examples/*.pl --quiet --time
