steps:
  test:
    when:
      - event: push
        branch: main
      - event: pull_request
        branch: main
    image: renjisann/docker-tree-sitter:0.0.1
    commands:
      - tree-sitter init-config
      - tree-sitter generate
      - tree-sitter test && tree-sitter parse examples/*.pl --quiet --time
  diff:
    when:
      - event: push
        branch: main
      - event: pull_request
        branch: main
    image: bitnami/git
    commands:
      - if [ "$(git status --porcelain)" ]; then exit 1; fi
